name: Linting

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Clone actorkeys
        uses: actions/checkout@v4
        with:
          repository: sdss/actorkeys
          ref: sdss5
          path: actorkeys

      - name: Install dependencies
        run: |
          pip install --upgrade wheel pip setuptools
          pip install .

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check src/hal
          ruff format --check src/hal
