name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    env:
      PYTHONPATH: '/home/runner/work/HAL/HAL/actorkeys/python'
      OBSERVATORY: 'APO'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Clone actorkeys
        uses: actions/checkout@v4
        with:
          repository: sdss/actorkeys
          ref: sdss5
          path: actorkeys

      - name: Install dependencies
        run: |
          pip install --upgrade wheel pip setuptools
          pip install .

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check src/hal

      - name: Lint with black
        run: |
          pip install black
          black --check src/hal

      - name: Test with pytest
        run: |
          pip install pytest pytest-mock pytest-asyncio pytest-cov
          pytest tests/
        env:
          OBSERVATORY: 'APO'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
