name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    env:
      PYTHONPATH: '/home/runner/work/HAL/HAL/actorkeys/python'
      OBSERVATORY: 'APO'

    steps:
      - uses: actions/checkout@v3

      - name: Cache Setup
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone actorkeys
        uses: actions/checkout@v3
        with:
          repository: sdss/actorkeys
          ref: sdss5
          path: actorkeys

      # - name: Setup node.js (for pyright)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      - name: Install dependencies
        run: |
          pip install --upgrade wheel pip setuptools
          pip install .

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff .

      - name: Lint with black
        run: |
          pip install black
          black --check src/hal

      # - name: Run type checking
      #   continue-on-error: true
      #   run: |
      #     npm install -g pyright
      #     pyright

      - name: Test with pytest
        run: |
          pip install pytest pytest-mock pytest-asyncio pytest-cov
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
